import { writeFileSync } from "node:fs";

import { canonicalJson } from "../src/canonical-json.ts";
import { goldenPolicy } from "../src/golden-policy.ts";
import { policyHash } from "../src/policy-hash.ts";
import { policySchema } from "../src/policy.ts";

// Run this after any change to the Policy schema or to goldenPolicy, and bump `version` when you
// do. Ticket 19 extends the fixture to bidHash, the Bid Commitment and the Bids Root.

const policy = policySchema.parse(goldenPolicy);

const fixture = {
  note: "Generated by scripts/generate-fixture.ts. Do not edit by hand.",
  policy,
  canonical: canonicalJson(policy),
  policyHash: policyHash(policy),
};

const target = new URL("../src/golden-policy.json", import.meta.url);

writeFileSync(target, `${JSON.stringify(fixture, null, 2)}\n`);

console.log(`wrote ${target.pathname}`);
console.log(`policyHash ${fixture.policyHash}`);
